### ISSUE TITLE
zone.is_on

### ISSUE THREAD

**Issue by fermatrix** [max13fr/AirzoneCloud#4]
Hi!

I would like all my zones to turn off at a certain time because people at the office forget to turn off the a/a when they leave.

I programmed something like this in a AWS Lambda:

```
for zone in api.all_zones:
        if zone.is_on == True:
            zone.turn_off()   
            msg_email += zone.name + " was ON we turn if OFF\n"
```

But there seems to be a problem because all muy zones appear to be OFF when in reality they are ON.

It seems to me like AirzoneCloud needs to reflesh the status of the Zones from the devices before asking if they are ON o OFF, there is a reference about Refresh in the documentation but I don´t know how should it be implemmented:

https://github.com/max13fr/AirzoneCloud/blob/master/API.md#refresh

When I launch the mobile app that Refresh is done by the app... and then my code works fine.

All the help is welcome :-)

**Comment by max13fr** [comment]
Hello,

I'm not really sure to understand your issue but I think it's come from the optimization of this lib : 
- when start the lib, we are loading all values and put it in local cache
- when calling an action, we just send the action to AirzoneCloud and update the value in local cache but not calling refresh() to avoid spaming the API if we are doing several actions like here at the same time. You just need to add a refresh when you're done all your actions.

The refresh is heavy because of the API (we need to do many several requests before finally loading zones and we can't refresh only one zone, we always refresh all zones of a device at the minimum).

Max

**Comment by fermatrix** [comment]
Hi Max, thanks a lot for your kind response. I will try using refresh() before checking if the zones are On or Off

**Comment by max13fr** [comment]
Hi,

Just tried to add a refresh_data param in all setters but I now remember the main issue : after sending an action, new data takes about 5 seconds to be updated by airzone device, so we need to sleep something likes 10 seconds before calling refresh() to be sure that the data is really updated.

Max

**Comment by max13fr** [comment]
Hello,

I just released a new version using the official Airzone API : https://developers.airzonecloud.com/docs/web-api/

It should fix this issue.

Max
